### ISSUE TITLE
Header elements not including margins matching GDS styles

### ISSUE THREAD

**Issue by stevesims** [UKHomeOffice/govuk-react#101]
GDS styles for `heading-*` classes have a `margin-top` set dependent upon the chosen size.  Currently these are not set by `Header`.

**Comment by stevesims** [comment]
It appears that the manner in which heading elements are styled has changed, and that the base sass in https://github.com/alphagov/govuk-frontend/blob/master/src/globals/core/_typography.scss has a `margin-top: 0` defined for headings

Will investigate further

**Comment by hom-bahrani** [comment]
Spoke to @Loque- about this yesterday, they appear to have a margin-bottom as well https://govuk-elements.herokuapp.com/typography/

**Comment by hom-bahrani** [comment]
check this out for instance, there's always a small margin between the herading and the start of the paragraph https://www.gov.uk/universal-credit

**Comment by Loque-** [comment]
@hom-bahrani I'm currently working through a solution for spacing sections apart without resorting to applying margin-top to elements. It might take a while to get the spec down and an implementation that the majority approves on released on govuk-react, however I hope to have some concept ideas using the spacing constants that anyone could drop in and use in the meantime. Will update here as soon as I have something worth sharing!

**Comment by Loque-** [comment]
@hom-bahrani I have created several examples for using the layout components, and spacing constants within govuk-react for rendering layout here: https://codesandbox.io/s/x917knwm4z

@stevesims I believe this implementation answers any concerns over the removal of margin-top from our components.
