### ISSUE TITLE
dont update doc images if not necessary

### ISSUE THREAD

**Issue by marksy** [UKHomeOffice/govuk-react#143]
not sure how this would be possible but it would be good to check to see: 
1. is there a component image? If so,
2. has the component changed since the last image was rendered? 

this is because i keep accidentally committing re-rendered images which aren't necessary (no visual diff). I guess this is mostly a user error, because it could be avoided if i (1. wasn't lazy and did `git add .`, 2. used a visual git application like git Tower which i have installed), but it would be catch if not too hard to do.

🐎

**Comment by penx** [comment]
if we generate images using docker then the binaries are unlikely to change

**Comment by penx** [comment]
this would be done using https://github.com/skalfyfan/dockerized-puppeteer as also mentioned in #65

**Comment by penx** [comment]
another option may be https://github.com/jxnblk/repng

**Comment by Loque-** [comment]
We don't generate images anymore \o/
