### ISSUE TITLE
Button types

### ISSUE THREAD

**Issue by marksy** [UKHomeOffice/govuk-react#202]
it might be useful to have Button types, such as;

- primary {blue}
- secondary {white with blue border}
- default {green}
- muted {grey}
- text {transparent with black or white text (depending on the bg somehow or manual)}

to be used like;
```
<Button styleType="primary">Okay</Button>
<Button styleType="muted">Cancel</Button>
```

Which would look like:
<img width="464" alt="screen shot 2018-04-12 at 12 00 18" src="https://user-images.githubusercontent.com/1695055/38673404-1f2561fc-3e49-11e8-8ecc-df6a0724ea97.png">

<img width="231" alt="screen shot 2018-04-12 at 12 08 52" src="https://user-images.githubusercontent.com/1695055/38673867-6c7ba0fa-3e4a-11e8-9b14-10b5bcc06182.png">

**Comment by penx** [comment]
are these established gds patterns anywhere? Could you link?

**Comment by marksy** [comment]
No, not established anywhere in particular, but maybe something to ask their team. These types of buttons (muted, primary [&/default] and secondary).

**Comment by Loque-** [comment]
Would an example of overwriting styles suffice (I'm part way through an example in storybook to demonstrate how to do this)? My current thinking is that it would be good to keep this repository as vanilla as possible, following established govuk patterns only.

**Comment by Loque-** [comment]
I finally created some [button examples on codesandbox](https://x917knwm4z.codesandbox.io/CustomElements), [editable here](https://codesandbox.io/s/x917knwm4z?module=%2Fsrc%2FPages%2FCustomElements.js).

Just incase it is useful I created a completely separate isolated example for the two custom element requests; https://codesandbox.io/s/n1p8kq2ypm
