### ISSUE TITLE
Implement storybook readme and/or info

### ISSUE THREAD

**Issue by penx** [UKHomeOffice/govuk-react#212]
If there is a readme for a component, show it in the storybook

https://github.com/tuchk4/storybook-readme

Or

https://github.com/storybooks/storybook/tree/master/addons/info

Consider how to integrate with existing documentation generator.

**Comment by Loque-** [comment]
I was looking at https://github.com/storybooks/storybook/tree/master/addons/info earlier and I thought it looked very useful for this project and could replace the current API.md?

A published storybook on Netlify, with contained docs and knobs might be more useful than the API.md alone (a possible justification to avoid investing in integrating the two together).

**Comment by penx** [comment]
yeah I think it would make API.md redundant
