### ISSUE TITLE
Use facepaint for breakpoints?

### ISSUE THREAD

**Issue by penx** [UKHomeOffice/govuk-react#251]
https://github.com/emotion-js/facepaint

though

https://emotion.sh/docs/extract-static

> extractStatic is not recommended because it breaks composition and other powerful patterns from libraries like facepaint. It is primarily available for historical reasons. It does not work with object styles

**Comment by Loque-** [comment]
I'm not a fan of the style personally and I also quite like what is implemented at the moment.

**Comment by Loque-** [comment]
I'm going to close this for the moment, but if we come back to discussing breakpoints I'm sure we will look at it.
