### ISSUE TITLE
TopNav and Layout should work together

### ISSUE THREAD

**Issue by penx** [UKHomeOffice/govuk-react#263]
If you have the following:

```html
<TopNav />
<Layout>
  <Header>Something</Header>
</Layout>
```

then Header should be appropriately positioned on all breakpoints.

...or we need a component other than Layout to do this.

**Comment by Loque-** [comment]
I have built this but didn't know there was a ticket for it;

https://github.com/UKHomeOffice/govuk-react/tree/master/components/main
Example;
https://x917knwm4z.codesandbox.io/

Currently updating all the layout docs, in hindsight, it may have been good to adjust `Layout`, but will fly with this for a little while as I am not sure we need `Layout` from the implementations I have seen so far.
