### ISSUE TITLE
Remove className property from components

### ISSUE THREAD

**Issue by Loque-** [UKHomeOffice/govuk-react#267]
I am not sure why className is added as a property to components, it doesn't appear to be used anywhere and could be passed down via props anyway, is it safe to remove?

My reasons for wanting to remove it are solely down to documenting each component. If I had a reasonable justification I could add this to the docs instead of removing it.

**Comment by stevesims** [comment]
Yes it shouldn’t need to be explicitly defined and passed through.

IIRC we support `className` to allow for some automation scenarios.

It can indeed just be passed through by spreading (unused) props, which should be default behaviour on most of our components.
