### ISSUE TITLE
Allow for font size variations in ListItem

### ISSUE THREAD

**Issue by stevesims** [UKHomeOffice/govuk-react#274]
It may be useful to allow for some font size variations for ListItem (we have a use-case that needs a smaller font size for display)

This is arguably part of a larger issue of allowing for font size variations across multiple different textual components

**Comment by Loque-** [comment]
You can do this by using the existing `ListItem` component and overriding the `fontSize` attribute;

https://codesandbox.io/s/n1p8kq2ypm
