### ISSUE TITLE
We should be router agnostic

### ISSUE THREAD

**Issue by stevesims** [UKHomeOffice/govuk-react#282]
Right now we have a dependency on `react-router-dom` - we should remove this.

Including it means we're not agnostic about routing and whilst our library users may also be using `react-router` they may be on a different version.  Additionally it stops us from being react-native compatible.

It's suggested that in the few components that require the `Link` component from `react-router-dom` (as I believe this is the only component that's being used) that we support passing in the `Link` component and fall-back to using plain `a` tags

**Comment by penx** [comment]
we were previously only including it as a devDependency, it was always the intention to never include it as a dependency

**Comment by penx** [comment]
in fact I can still only find references to it in stories...
