### ISSUE TITLE
Missing version 1 components

### ISSUE THREAD

**Issue by taranchauhan** [UKHomeOffice/govuk-react#298]
@penx @stevesims @Loque- 

I have noticed the following components are missing from the [V1](https://github.com/UKHomeOffice/govuk-react/issues/61) goal.

[GOV UK Elements Typography](https://govuk-elements.herokuapp.com/typography/#typography-body-copy)
- WarningText 
- HiddenText 

[GOV UK Elements Data](https://govuk-elements.herokuapp.com/data)
- DataVisualisation

[GOV UK Elements Icons Images](https://govuk-elements.herokuapp.com/icons-images/)
- Image (3:2 Aspect Ratio)

[GOV UK Elements Errors](https://govuk-elements.herokuapp.com/errors)
- ErrorSummaryBox

Is there any particular reason for this or were these either just missed or introduced as new after the [issue](https://github.com/UKHomeOffice/govuk-react/issues/61) was created.

Could these be a possible target for V2?

**Comment by Joe-Brady** [comment]
ErrorSummaryBox would be very useful for us as a priority!

**Comment by Loque-** [comment]
Thanks @taranchauhan! I've added these to #61 as they should be a part of version 1, excluding the image as it could be time consuming for us to get this right as a component (`srcset` for example), but also easy for people to implement a 4:3 image in the meantime or create their own image component.
