### ISSUE TITLE
Re-link Chromatic

### ISSUE THREAD

**Issue by Loque-** [UKHomeOffice/govuk-react#301]
Since moving to the UKHomeOffice account we no longer have Chromatic, which is sorely missed. It would be fantastic to re-integrate this.

**Comment by Loque-** [comment]
Alright! We have authorisation for Chromatic on UKHomeOffice which is awesome. The nest step is to either reconfigure the existing account, or to create a new instance on Chromatic.

https://github.com/UKHomeOffice/application-container-platform-bau/issues/3665#issuecomment-400599398

**Comment by penx** [comment]
closed in #400
