### ISSUE TITLE
Hidden text

### ISSUE THREAD

**Issue by anishamalde** [UKHomeOffice/govuk-react#303]
No component for hidden text exists, needed for FSA
![screen shot 2018-05-31 at 14 37 29](https://user-images.githubusercontent.com/39306477/40785359-37aff756-64e0-11e8-9516-d4d8020749cd.png)

**Comment by Loque-** [comment]
Thanks Anisha, we will certainly add it to the list of components for development (I thought it may have been listed already however I cannot see it there yet).

If it is something that you need to use quickly however I would suggest you or your team create the component in a fork of this project and make a PR, as this will be fastest way for you to use it. I can help with this process and am available on some of the same slack channels as you also!

I am hoping in the near future that we use the projects feature in Github so anyone looking at this project can see a prioritised backlog to get an idea of what is in progress and when something may be available.

**Comment by Loque-** [comment]
Just incase anyone else is looking to do something like this and would like to make the component as a PR the following example may help get them going: https://codesandbox.io/s/k5zz5k69o3

@taranchauhan mentioned the missing component from our list yesterday in this issue: #298

**Comment by Loque-** [comment]
Just to follow up after a call with Joe from the FSA team, he mentioned that the example was not using the `details` and `summary` tags; I hadn't heard/seen these tags before and figured I could make a test with them to help anyone else doing the same thing: https://codesandbox.io/s/k5zz5k69o3
