### ISSUE TITLE
Multiple instances of dev server doesnt work

### ISSUE THREAD

**Issue by marksy** [UKHomeOffice/govuk-react#335]
If you have another dev server running on `9009` the instance won't serve.

Would be good to run it on a different port if that port is already taken.

Example:
I was running a fork of the `govuk-react` i made when i left the project in April 2018 and was running it. Then tried to run the UKHomeOffice `govuk-react` project and it failed because the port was already in use.

**Comment by Loque-** [comment]
This is something for Storybook I think? We simply kick that off when developing the component library (check `package.json` for `start`).

If it is an issue and you need to have two projects running and you cannot/do not want to change the port of the other project you can probably set the port manually under the `start` script in `package.json` for that use case following documentation from Storybook.

**Comment by Loque-** [comment]
From here: https://storybook.js.org/configurations/cli-options/

And then looking at this: https://github.com/UKHomeOffice/govuk-react/blob/master/packages/storybook/package.json#L61

If you need to use a different port, adjust the port numbers used in that `package.json` and you are good to go! <3
