### ISSUE TITLE
Triangle on HiddenText is being removed in some browsers

### ISSUE THREAD

**Issue by Joe-Brady** [UKHomeOffice/govuk-react#339]
Looks like there is a feature of the `<summary>` element that allows you to remove the twisty triangle by changing the `display` type in CSS.

However, this feature isn't yet in Chrome by the looks of it, so we only just noticed that the triangle is missing in Firefox, for example!

Looks like the `display: inline-block` is the culprit. Its default is `list-item`:

"Per the HTML specification, the default style for `<summary>` elements includes `display: list-item`. This makes it possible to change or remove the icon displayed as the disclosure widget next to the label from the default, which is typically a triangle."

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/summary

<img width="730" alt="screen shot 2018-06-20 at 15 06 16" src="https://user-images.githubusercontent.com/20062773/41664016-a999e39c-749c-11e8-9190-c5b857bbee95.png">
<img width="1573" alt="screen shot 2018-06-20 at 15 06 39" src="https://user-images.githubusercontent.com/20062773/41664017-a9c9e290-749c-11e8-9b0b-db652623732f.png">

**Comment by igloosi** [comment]
just to note that summary implementation in GOV.UK Frontend is not affected by this change
