### ISSUE TITLE
packages/api-docs could possibly be reused for govuk-frederic

### ISSUE THREAD

**Issue by taranchauhan** [UKHomeOffice/govuk-react#346]
index.js in api-docs Line 15 is hardcoded to govuk-react

```
const components = require(‘govuk-react’);
```

If this was dynamic, then it would allow us to reuse it. However, dynamic variables in requires cause an issue with Webpack at build time.

Since Webpack is running in build-time, it can’t figure out which modules to bundle when the name is a dynamic variable. You can give it hints by specifying part of the path (for example, if you know all the modules are in a single directory).

This is an issue to consider.

**Comment by Loque-** [comment]
Migrated issue to: https://github.com/stevesims/govuk-frederic/issues/6
