### ISSUE TITLE
Issue with Radio Buttons in Final Form

### ISSUE THREAD

**Issue by dsm23** [UKHomeOffice/govuk-react#349]
Warning: You must pass `type="radio` prop to your Field(name) component.

Without it we don't know how to unpack your `value` prop - "undefined"

^^Console error that is displayed for RadioGroup within the Final Form Wrapper

https://github.com/UKHomeOffice/govuk-react/blob/master/components/radio/src/stories.js

**Comment by dsm23** [comment]
no need, the problem is occurring in storybook:
https://ukhomeoffice.github.io/govuk-react/?knob-Children=Back&selectedKind=Form%2FRadio%2FExamples&selectedStory=Usage%20with%20Final%2FRedux%20Form%20-%20multi%20checkbox%20validation&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

**Comment by Loque-** [comment]
I don't get a warning there;

<img width="1136" alt="screen shot 2018-06-27 at 09 49 23" src="https://user-images.githubusercontent.com/657572/41963399-62caa8c2-79ef-11e8-9fbc-7289a93e0b21.png">

**Comment by Loque-** [comment]
Confirmed as not an issue currently - thanks again for creating the ticket tho, keep them coming!
