### ISSUE TITLE
Issue with Radio Button styling

### ISSUE THREAD

**Issue by dsm23** [UKHomeOffice/govuk-react#350]
The style of the Radio Buttons in storybook do not resemble the radio buttons of GDS:

GDS: https://govuk-elements.herokuapp.com/form-elements/#form-radio-buttons

Storybook: 
https://ukhomeoffice.github.io/govuk-react/?knob-Children=Back&selectedKind=Form%2FRadio%2FExamples&selectedStory=Radio%20stacked&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

source:
https://github.com/UKHomeOffice/govuk-react/blob/master/components/radio/src/index.js

**Comment by Loque-** [comment]
Many thanks for the issue, unfortunately I can't immediately see the difference - what is not the same between the two?

**Comment by Loque-** [comment]
Offline update;

 - There is an unwanted white dot in the middle of radio buttons in chrome
 - The inner circle is off by 1 pixel and is therefore not completely centered within the outer circle.

**Comment by Joe-Brady** [comment]
I had noticed the white dot - tried to look into that one but couldn't see where it was happening?!

**Comment by Loque-** [comment]
(my bad closing this early - I thought a fix was in already, but the PR was) - Just left some feedback on it as I am a little confused as to why we wouldn't use px on these. Cheers!
