### ISSUE TITLE
start prop error for button component

### ISSUE THREAD

**Issue by hom-bahrani** [UKHomeOffice/govuk-react#359]
I get the following error when rendering a simple button, whether a start prop is passed or not. `Warning: Received false for a non-boolean attribute start`.

**Comment by Loque-** [comment]
Thanks for the report, could you provide an example on codesandbox.io? 

I don't get the error: https://codesandbox.io/s/n1p8kq2ypm - maybe this is from an older version?

**Comment by Joe-Brady** [comment]
I also get this error - was planning to fix it at some point soon, maybe next sprint. But will keep an eye out if someone else gets to it first!

**Comment by Loque-** [comment]
Ah ok, yea! I remember what this was related to. I must have fixed it here; https://github.com/UKHomeOffice/govuk-react/pull/345/commits/9db6a69c283bc4d9b62aedd37164cb39544bfea6#diff-97f3eb27137c775b8921629bfd4db49eL57 when cleaning the tests in the last release (as I was getting the warning/error in the test suite), sorry @hom-bahrani I completely forgot that.

As you can see from those changes, we may need to apply props only used for styling under a different name to the component first, before then using this alternate prop-name in the emotion definition. Looks like another medium post just waiting to happen, but I'd need to better (understand and) describe the issue, probably :`P - I did go through this with Steve and Gavin and we saw some rather funky alternate solutions, however this one I think is easily the quickest and most elegant.

**Comment by Joe-Brady** [comment]
Great stuff, thanks for the update and fix

**Comment by Loque-** [comment]
Not sure if it is worth creating a ticket to apply this formula to all props being used with emotion, would be nice to use it as a standard IMHO.

**Comment by hom-bahrani** [comment]
@Loque- Thanks Toby your a legend!
