### ISSUE TITLE
Allow mobile menu to be expanded without client side JavaScript

### ISSUE THREAD

**Issue by Loque-** [UKHomeOffice/govuk-react#412]
We previously used the CSS adjacent sibling selector and a hidden checkbox HTML node to manage the state of the mobile menu navigation (providing no-js support for the mobile menu). This is being replaced with React state as it removes the syntax structure restriction imposed by using the adjacent sibling selector.

This change introduces a challenge; how should we provide a progressively enhanced mobile menu if a static version of the page is served but javascript is either not available or the javascript counterpart to the page is not delivered to the user?

A positive side effect to this change is that it is also a step towards supporting React Native, as the adjacent sibling selector would not be supported in this environment.

**Comment by penx** [comment]
Positives for old approach:
- doesn't rely on client side JavaScript being loaded, good for universal rendering when the JS has not been delivered to the browser
- allows a user to start interacting before loading all JS, e.g. on a slow connection

Positives for new approach in #411 :
- doesn't rely on browser only CSS features, good for React native
- resolved #409 (no associated bug unfortunately)


I think both approaches could be deemed better depending on usage of the library. Happy to go with the new approach for now, but this ticket is to track there is remaining discussion to be had around whether there is an optimal solution that would suit both use cases

**Comment by Loque-** [comment]
I figured that we can add the checkbox alongside the state ~ it does need a review as I could be missing something; specifically I am thinking about the fact I have not yet linked the checkbox to the state - slightly tricky for me to theory fix this as I don't have an example of the component rendered on the server, served to the user initially, and then React being loaded clientside.
