### ISSUE TITLE
Rows in summary table dont text wrap to size of table

### ISSUE THREAD

**Issue by anishamalde** [UKHomeOffice/govuk-react#414]
![screen shot 2018-09-19 at 13 36 20](https://user-images.githubusercontent.com/39306477/45753816-d3e0ef80-bc11-11e8-8792-bf8be1396874.png)

**Comment by penx** [comment]
Maybe I'm mistaken you you seem to be inferring that the 109.58..... figure should wrap to a new line?

In html, text won't wrap if there isn't white space, so this is behaving as expected.

Is there a proposed behaviour?

Things I could think of:

- using overflow hidden, though I'd be against this
- parent app can put a child component in a row with overflow hidden or scroll-x or similar

**Comment by penx** [comment]
Toby says we can use word wrap :-)

**Comment by Loque-** [comment]
I reckon `word-break: break-word;` would do it : )
