### ISSUE TITLE
use 'test' rather than 'match'

### ISSUE THREAD

**Issue by dsm23** [UKHomeOffice/govuk-react#429]
https://github.com/UKHomeOffice/govuk-react/blob/master/components/paragraph/src/link-renderer.js

ternary operator on line 9 uses str.match(regex) for the conditional,

str.match(regex) returns an array or null while regex.test(str) returns a bool

**Comment by penx** [comment]
Sounds good. Want to raise a PR?

**Comment by penx** [comment]
You can edit inline on github and propose a pr btw

**Comment by dsm23** [comment]
Do I need to be aware of any scripts that need to be run before making a commit in a PR?

**Comment by penx** [comment]
Our CI should run all the required checks. As long as there are appropriate unit test in place for this component I say go for it by editing inline on github

**Comment by penx** [comment]
Paragraph component no longer uses regex match
